# Generated by Django 5.2 on 2025-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_car_carbrand_carmodel_delete_bb_car_brand_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото машины'),
        ),
    ]
